"""empty message

Revision ID: c4f2892f0153
Revises: 
Create Date: 2024-12-04 22:28:00.851179

"""
from alembic import op
import sqlalchemy as sa


revision = 'c4f2892f0153'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('account_type', sa.Enum('BANK', 'CASH', 'CRYPTO', name='accounttype'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_table('bank_account',
    sa.Column('bank', sa.Enum('TINKOFF', 'SBER', 'ALFA', name='bank'), nullable=False),
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_account_id'), 'bank_account', ['id'], unique=False)
    op.create_table('cash_account',
    sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_account_id'), 'cash_account', ['id'], unique=False)
    op.create_table('category',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('crypto_account',
    sa.Column('currency', sa.Enum('BTC', 'ETH', 'USDT', name='cryptocurrency'), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_account_id'), 'crypto_account', ['id'], unique=False)
    op.create_table('transaction',
    sa.Column('amount', sa.DECIMAL(precision=20, scale=2), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_crypto_account_id'), table_name='crypto_account')
    op.drop_table('crypto_account')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_cash_account_id'), table_name='cash_account')
    op.drop_table('cash_account')
    op.drop_index(op.f('ix_bank_account_id'), table_name='bank_account')
    op.drop_table('bank_account')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###