version: '3.3'

services:
  gateway:
    command: uvicorn config.fastapi:app --host 0.0.0.0 --port 8000 --reload
    build:
      dockerfile: ./Dockerfile
      context: ./gateway
    ports:
      - 8000:8000
    volumes:
      - ./gateway:/server
    environment:
      RMQ_URI: amqp://${RMQ_USER}:${RMQ_PASSWORD}@rmq:5672/${RMQ_VHOST}
    depends_on:
      rmq:
        condition: service_healthy

  users:
    command: faststream run config.faststream:app --reload
    build:
      dockerfile: ./Dockerfile
      context: ./users
    volumes:
      - ./users:/server
    environment:
      POSTGRES_URI: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${USERS_DB}
      RMQ_URI: amqp://${RMQ_USER}:${RMQ_PASSWORD}@rmq:5672/${RMQ_VHOST}
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      rmq:
        condition: service_healthy

  mails:
    command: faststream run config.faststream:app --reload
    build:
      dockerfile: ./Dockerfile
      context: ./mails
    volumes:
      - ./mails:/server
    environment:
      RMQ_URI: amqp://${RMQ_USER}:${RMQ_PASSWORD}@rmq:5672/${RMQ_VHOST}
      SMTP_HOSTNAME: ${SMTP_HOSTNAME}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_START_TLS: ${SMTP_START_TLS}
      SMTP_USE_TLS: ${SMTP_USE_TLS}
    depends_on:
      rmq:
        condition: service_healthy

  postgres:
    image: postgres:16.4-alpine
    ports:
      - 5432:5432
    user: ${POSTGRES_USER}
    volumes:
      - ./postgres/create_databases.sh:/docker-entrypoint-initdb.d/create_databases.sh
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASES: ${USERS_DB}
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 10s
      retries: 40

  rmq:
    image: rabbitmq:4.0.2-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RMQ_VHOST}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 2s
      timeout: 10s
      retries: 40
